CREATE TABLE Records(
	RecordID INT NOT NULL AUTO_INCREMENT,
	CONTROL_LIMB INT DEFAULT NULL,
	AFFECTED_LIMB INT DEFAULT NULL,
	DATE VARCHAR(10) DEFAULT NULL,
	ILDIFF INT DEFAULT NULL,
	PatientID INT(11) NOT NULL,
	PRIMARY KEY (RecordID)
	);

INSERT INTO `Patients` (`Name`, `Address`) VALUES ('$n', '$a');";

INSERT INTO Records (CONTROL_LIMB, AFFECTED_LIMB, PatientID)
VALUES (5, 10, 1);

INSERT INTO Records (CONTROL_LIMB, AFFECTED_LIMB, PatientID)
VALUES (5, 13, 1);

INSERT INTO Records (CONTROL_LIMB, AFFECTED_LIMB, PatientID)
VALUES (5, 12, 2);

INSERT INTO Records (CONTROL_LIMB, AFFECTED_LIMB, PatientID)
VALUES (5, 12, 3);